 # [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT medicwhizz_web.wsgi
threadsafe: yes

automatic_scaling:
  max_num_instances: 100

runtime_config:
  python_version: 3.6
# [END runtime]